export const CATALOG_CATEGORIES = [
  "Todos",
  "Institucional",
  "Nobreak",
  "Transformador",
  "Senoidal",
  "Strong",
  "Proteção",
] as const;

export type CatalogCategory = Exclude<(typeof CATALOG_CATEGORIES)[number], "Todos">;

export type Catalog = {
  slug: string;
  title: string;
  description: string;
  category: CatalogCategory;
  pdf: string;
  cover: string;
};

const PDF = "https://www.rbfbrasil.com.br/assets/pdf";
const COVER = "/images/catalogos";

export const CATALOGS: Catalog[] = [
  {
    slug: "catalogo-personalizado",
    title: "Catálogo Personalizado",
    description: "Visão geral das linhas RBF do Brasil para especificação e orçamento.",
    category: "Institucional",
    pdf: `${PDF}/catalogo-rbf-do-brasil-personalizado.pdf`,
    cover: `${COVER}/capa-catalogo-personalizado.png`,
  },
  {
    slug: "guia-pos-venda",
    title: "Guia de Pós-venda",
    description: "Orientações de assistência, manutenção e relacionamento técnico.",
    category: "Institucional",
    pdf: `${PDF}/pos-venda-rbf-do-brasil-2022.pdf`,
    cover: `${COVER}/pos-venda.png`,
  },
  {
    slug: "dcpt-rd-10-1000kva",
    title: "Modelo DCPT-RD 10-1000 kVA",
    description: "Nobreak trifásico dupla conversão de alta potência.",
    category: "Nobreak",
    pdf: `${PDF}/modelo-dcpt-rd-10-1000kva.pdf`,
    cover: `${COVER}/modelo-dcpt-rd-10-1000kva.png`,
  },
  {
    slug: "dcat-f",
    title: "Modelo DCAT-F RBF",
    description: "Transformador isolador para proteção e adequação de tensão.",
    category: "Transformador",
    pdf: `${PDF}/modelo-dcat-f-rbf.pdf`,
    cover: `${COVER}/modelo-dcat-f-rbf.png`,
  },
  {
    slug: "dcp-a-10-120kva",
    title: "Modelo DCP-A 10-120 kVA",
    description: "Nobreak online dupla conversão para cargas críticas.",
    category: "Nobreak",
    pdf: `${PDF}/modelo-dcp-a-10-120kva.pdf`,
    cover: `${COVER}/modelo-dcp-a-10-120kva.png`,
  },
  {
    slug: "dcp-a-10-60kva",
    title: "Modelo DCP-A 10-60 kVA",
    description: "Nobreak online dupla conversão de médio porte.",
    category: "Nobreak",
    pdf: `${PDF}/modelo-dcp-a-10-60kva.pdf`,
    cover: `${COVER}/modelo-dcp-a-10-60kva.png`,
  },
  {
    slug: "dcp-r-10-1000kva",
    title: "Modelo DCP-R 10-1000 kVA",
    description: "Nobreak trifásico rack/industrial de alta capacidade.",
    category: "Nobreak",
    pdf: `${PDF}/modelo-dcp-r-10-1000kva.pdf`,
    cover: `${COVER}/modelo-dcp-r-10-1000kva.png`,
  },
  {
    slug: "dcp-r-10-500kva",
    title: "Modelo DCP-R 10-500 kVA",
    description: "Nobreak trifásico para infraestrutura e datacenter.",
    category: "Nobreak",
    pdf: `${PDF}/modelo-dcp-r-10-500kva.pdf`,
    cover: `${COVER}/modelo-dcp-r-10-500kva.png`,
  },
  {
    slug: "dcp-r-10-200kva",
    title: "Modelo DCP-R 10-200 kVA",
    description: "Nobreak trifásico dupla conversão 10 a 200 kVA.",
    category: "Nobreak",
    pdf: `${PDF}/modelo-dcp-r10-200kva.pdf`,
    cover: `${COVER}/modelo-dcp-r10-200kva.png`,
  },
  {
    slug: "dcp-r-10-100kva",
    title: "Modelo DCP-R 10-100 kVA",
    description: "Nobreak trifásico para operação crítica.",
    category: "Nobreak",
    pdf: `${PDF}/modelo-dcp-r-10-100kva.pdf`,
    cover: `${COVER}/modelo-dcp-r-10-100kva.png`,
  },
  {
    slug: "dcp-r-10-60kva",
    title: "Modelo DCP-R 10-60 kVA",
    description: "Nobreak trifásico compacto de alta disponibilidade.",
    category: "Nobreak",
    pdf: `${PDF}/modelo-dcp-r-10-60kva.pdf`,
    cover: `${COVER}/modelo-dcp-r-10-60kva.png`,
  },
  {
    slug: "estabilizador-new-strong-trifasico",
    title: "Estabilizador New Strong Trifásico",
    description: "Estabilizador trifásico para grandes operações industriais.",
    category: "Strong",
    pdf: `${PDF}/estabilizador-new-strong-trifasico.pdf`,
    cover: `${COVER}/estabilizador-new-strong-trifasico.png`,
  },
  {
    slug: "sbf",
    title: "Modelo SBF",
    description: "Nobreak senoidal para estações e equipamentos sensíveis.",
    category: "Senoidal",
    pdf: `${PDF}/modelo-sbf.pdf`,
    cover: `${COVER}/modelo-sbf.png`,
  },
  {
    slug: "dca-novo",
    title: "Modelo DCA (novo)",
    description: "Linha DCA atualizada para proteção senoidal.",
    category: "Senoidal",
    pdf: `${PDF}/modelo-dca-novo.pdf`,
    cover: `${COVER}/modelo-dca-novo.png`,
  },
  {
    slug: "spbr-novo",
    title: "Modelo SPBR (novo)",
    description: "Nobreak senoidal interativo da linha SPBR.",
    category: "Senoidal",
    pdf: `${PDF}/modelo-spbr-novo.pdf`,
    cover: `${COVER}/modelo-spbr-novo.png`,
  },
  {
    slug: "dcp-c-5-10kva",
    title: "Modelo DCP-C 5 a 10 kVA",
    description: "Nobreak dupla conversão compacto 5 a 10 kVA.",
    category: "Nobreak",
    pdf: `${PDF}/modelo-dcp-c-5-a-10kva.pdf`,
    cover: `${COVER}/modelo-dcp-c-5-a-10kva.png`,
  },
  {
    slug: "robust-monofasico",
    title: "Robust Monofásico",
    description: "Estabilizador Robust para operação monofásica intensa.",
    category: "Strong",
    pdf: `${PDF}/robust-monofasico.pdf`,
    cover: `${COVER}/robust-monofasico.png`,
  },
  {
    slug: "robust-trifasico",
    title: "Robust Trifásico",
    description: "Estabilizador Robust para cargas trifásicas.",
    category: "Strong",
    pdf: `${PDF}/robust-trifasico.pdf`,
    cover: `${COVER}/robust-trifasico.png`,
  },
  {
    slug: "dcat-xm",
    title: "Modelo DCAT-XM",
    description: "Transformador isolador da linha DCAT-XM.",
    category: "Transformador",
    pdf: `${PDF}/modelo-dcat-xm.pdf`,
    cover: `${COVER}/modelo-dcat-xm.png`,
  },
  {
    slug: "dca-rt",
    title: "Modelo DCA-RT",
    description: "Nobreak senoidal rack-tower DCA-RT.",
    category: "Senoidal",
    pdf: `${PDF}/modelo-dca-rt.pdf`,
    cover: `${COVER}/modelo-dca-rt.png`,
  },
  {
    slug: "isu",
    title: "Modelo ISU",
    description: "Linha ISU para proteção de energia condicionada.",
    category: "Senoidal",
    pdf: `${PDF}/modelo-isu.pdf`,
    cover: `${COVER}/modelo-isu.png`,
  },
  {
    slug: "sba",
    title: "Modelo SBA",
    description: "Nobreak senoidal da linha SBA.",
    category: "Senoidal",
    pdf: `${PDF}/modelo-sba.pdf`,
    cover: `${COVER}/modelo-sba.png`,
  },
  {
    slug: "dcat-rt",
    title: "Modelo DCAT-RT",
    description: "Transformador isolador DCAT formato rack-tower.",
    category: "Transformador",
    pdf: `${PDF}/modelo-dcat-rt.pdf`,
    cover: `${COVER}/modelo-dcat-rt.png`,
  },
  {
    slug: "dcv",
    title: "Modelo DCV",
    description: "Nobreak da linha DCV para proteção contínua.",
    category: "Senoidal",
    pdf: `${PDF}/modelo-dcv.pdf`,
    cover: `${COVER}/modelo-dcv.png`,
  },
  {
    slug: "dcat-lv-220-127",
    title: "Modelo DCAT LV 220V-127V",
    description: "Transformador isolador para adequação 220/127 V.",
    category: "Transformador",
    pdf: `${PDF}/modelo-dcat-lv-220v-127v.pdf`,
    cover: `${COVER}/modelo-dcat-lv-220v-127v.png`,
  },
  {
    slug: "senoidal-torre",
    title: "Nobreak Senoidal Torre",
    description: "Nobreak senoidal em gabinete torre para estações e clínicas.",
    category: "Senoidal",
    pdf: `${PDF}/nobreak-senoidal-torre.pdf`,
    cover: `${COVER}/nobreak-senoidal-torre.png`,
  },
  {
    slug: "dcp-5-10kva",
    title: "Modelo DCP 5 a 10 kVA",
    description: "Nobreak dupla conversão 5 a 10 kVA.",
    category: "Nobreak",
    pdf: `${PDF}/catalogo-rbf-do-brasil-modelo-dcp-5-a-10kva.pdf`,
    cover: `${COVER}/modelo-dcp-5-a-10kva.png`,
  },
  {
    slug: "dcp-e",
    title: "Modelo DCP E",
    description: "Nobreak online da linha DCP E.",
    category: "Nobreak",
    pdf: `${PDF}/catalogo-rbf-do-brasil-modelo-dcp-e.pdf`,
    cover: `${COVER}/modelo-dcp-e.png`,
  },
  {
    slug: "dcp-m",
    title: "Modelo DCP M",
    description: "Nobreak online da linha DCP M.",
    category: "Nobreak",
    pdf: `${PDF}/catalogo-rbf-do-brasil-modelo-dcp-m.pdf`,
    cover: `${COVER}/modelo-dcp-m.png`,
  },
  {
    slug: "dps-isolar",
    title: "DPS Isolar",
    description: "Protetor contra surtos, queimas e raios da linha Isolar.",
    category: "Proteção",
    pdf: `${PDF}/catalogo-rbf-do-brasil-modelo-dps-isolar.pdf`,
    cover: `${COVER}/dps-isolar.png`,
  },
  {
    slug: "dca",
    title: "Modelo DCA",
    description: "Nobreak senoidal da linha DCA.",
    category: "Senoidal",
    pdf: `${PDF}/catalogo-rbf-do-brasil-modelo-dca.pdf`,
    cover: `${COVER}/modelo-dca.png`,
  },
  {
    slug: "linha-strong",
    title: "Linha Strong",
    description: "Nobreaks e estabilizadores Strong para operação intensa.",
    category: "Strong",
    pdf: `${PDF}/catalogo-rbf-do-brasil-linha-strong.pdf`,
    cover: `${COVER}/linha-strong.png`,
  },
  {
    slug: "sb",
    title: "Modelo SB",
    description: "Nobreak senoidal compacto da linha SB.",
    category: "Senoidal",
    pdf: `${PDF}/catalogo-rbf-do-brasil-modelo-sb.pdf`,
    cover: `${COVER}/modelo-sb.png`,
  },
  {
    slug: "spbr",
    title: "Modelo SPBR",
    description: "Nobreak senoidal interativo SPBR.",
    category: "Senoidal",
    pdf: `${PDF}/catalogo-rbf-do-brasil-modelo-spbr.pdf`,
    cover: `${COVER}/modelo-spbr.png`,
  },
  {
    slug: "dcat-rm",
    title: "Modelo DCAT RM",
    description: "Transformador isolador DCAT formato rack.",
    category: "Transformador",
    pdf: `${PDF}/catalogo-rbf-do-brasil-modelo-dcat-rm.pdf`,
    cover: `${COVER}/modelo-dcat-rm.png`,
  },
  {
    slug: "dcat-220-127",
    title: "Modelo DCAT 220-127 V",
    description: "Transformador isolador para conversão 220/127 V.",
    category: "Transformador",
    pdf: `${PDF}/catalogo-rbf-do-brasil-modelo-dcat-220-127v.pdf`,
    cover: `${COVER}/modelo-dcat-220-127v.png`,
  },
  {
    slug: "dcat-380-220",
    title: "Modelo DCAT 380-220 V",
    description: "Transformador isolador para conversão 380/220 V.",
    category: "Transformador",
    pdf: `${PDF}/catalogo-rbf-do-brasil-modelo-dcat-380-220v.pdf`,
    cover: `${COVER}/modelo-dcat-380-220v.png`,
  },
  {
    slug: "dcpt",
    title: "Modelo DCPT",
    description: "Nobreak trifásico dupla conversão da linha DCPT.",
    category: "Nobreak",
    pdf: `${PDF}/catalogo-rbf-do-brasil-modelo-dcpt.pdf`,
    cover: `${COVER}/modelo-dcpt.png`,
  },
];
